#!/bin/bash

sudo hostnamectl set-hostname SipRouter

sudo cat <<EOT > /etc/netplan/00-installer-config.yaml
network:
  ethernets:
    outside:
      dhcp4: true
      match:
        macaddress: $1
      set-name: outside
    gateway:
      addresses:
        - 10.0.1.254/24
      match:
        macaddress: $2
      set-name: gateway
  version: 2
EOT

sudo netplan apply
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -p

echo "Konfiguration abgeschlossen."
